chat:
  enabled: true
antiSpam:
  enabled: true
  cooldown: 3
antiFlood:
  enabled: true
  minMessageLength: 20
  maxCapsPercent: 50
antiCaps:
  enabled: true
antiSwearing:
  enabled: true
format:
  default: "&8[G]{PLAYER}&7: "
  vip: "<&#EFB22A>[VIP]{PLAYER}</&#FDD16F>&7: "
  svip: "<&#FB9208>[sVIP]{PLAYER}</&#FDA96F>&7: "
  elita: "<&#3D29BE>[ELITA]{PLAYER}</&#3BDFFF>&8: &#78E9FF"
  admin: "<&#FB0808>[Admin]{PLAYER}</&#EFB22A>&8: &c"

autoMessage:
  interval: 30
  messages:
    0:
      enable: true
      sound:
        name: 'AMBIENT_NETHER_WASTES_LOOP'
        volume: 0.5
        pitch: 0.5
      messages:
        - "[]================================[]"
        - "<center>&#acbbcasssgggaw"
        - "X<center><&#323232>adawdwadwa</&#aaaaaa></center>X"
        - "[]================================[]"
      commands:
        - "bc elo melo"